### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '...Patched\\patched.log'

### ISSUE THREAD

**Issue by dsnum1** [patched-codes/patchwork#104]
I installed PatchFlow just to play around. Upon installation, I got the error-- `Patched/patched.log` file not found.  To fix it I had to manually add the folder Patched to `AppData/Roaming`. Maybe I should have run the command using administrator.

```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\patched-cli.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Python310\lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Python310\lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Python310\lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "C:\Python310\lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "C:\Python310\lib\site-packages\patched_cli\app.py", line 199, in <lambda>
    callback=lambda x, y, z: init_cli_logger(x),
  File "C:\Python310\lib\site-packages\patched_cli\utils\logging.py", line 48, in init_cli_logger
    fh = logging.FileHandler(LOG_FILE, mode="w")
  File "C:\Python310\lib\logging\__init__.py", line 1167, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python310\lib\logging\__init__.py", line 1197, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Divyansh Sharma\\AppData\\Roaming\\Patched\\patched.log'
```

**Comment by codelion** [comment]
I think this issue happens on windows, we get the home directory here - https://github.com/patched-codes/patchwork/blob/943818100e8cdacdc2cd8fab3c7ae409b6ff275d/patchwork/managed_files.py#L5C26-L5C37

We may need to create the directory if it doesn't exist:

```
# Ensure the directory exists
HOME_FOLDER.mkdir(parents=True, exist_ok=True)
```

@dsnum1 is it something you can help implement?

**Comment by dsnum1** [comment]
Okay I'll try.

**Comment by dsnum1** [comment]
My token has not been working. I need to pass this authentication to see if my code does not break anything: 
![image](https://github.com/patched-codes/patchwork/assets/41879236/8ca09ef6-d7c0-4813-9393-f8a95d15a8f7)

**Comment by codelion** [comment]
@whoisarpit Can you see if there an issue with the `patched_api_key` token? 

@dsnum1 Meanwhile, you can submit a PR with your changes. I can help test it for you.

**Comment by codelion** [comment]
#114 fixes this.
