### ISSUE TITLE
patchwork --version error

### ISSUE THREAD

**Issue by codelion** [patched-codes/patchwork#4]
(patchwork-cli-py3.10) user@Users-MBP patchwork % patchwork --version
Traceback (most recent call last):
  File "/Users/user/Documents/GitHub/patchwork/.venv/bin/patchwork", line 6, in <module>
    sys.exit(cli())
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/user/Documents/GitHub/patchwork/.venv/lib/python3.10/site-packages/click/decorators.py", line 506, in callback
    raise RuntimeError(
RuntimeError: 'patchwork' is not installed. Try passing 'package_name' instead.

**Comment by codelion** [comment]
The following files in the repository may be relevant to the issue:

------

* patchwork/app.py
* patchwork/common/client/scm.py
* patchwork/steps/CallCode2Prompt/CallCode2Prompt.py
* patchwork/steps/ExtractDiff/ExtractDiff.py
* patchwork/patchflows/DependencyUpgrade/DependencyUpgrade.py

**Comment by codelion** [comment]
The following files in the repository may be relevant to the issue:

------

* patchwork/app.py
* patchwork/steps/ExtractPackageManagerFile/ExtractPackageManagerFile.py
* patchwork/patchflows/ResolveIssue/ResolveIssue.py
* patchwork/steps/ExtractDiff/ExtractDiff.py
* patchwork/patchflows/GenerateREADME/GenerateREADME.py

**Comment by codelion** [comment]
Fixed in #55 #57
